Add support for expiring netflow files

diff --git a/files/etc/init.d/lw_nfcapd b/files/etc/init.d/lw_nfcapd
--- a/files/etc/init.d/lw_nfcapd
+++ b/files/etc/init.d/lw_nfcapd
@@ -21,10 +21,20 @@ validate_nfcapd_section() {
                 'enabled:bool' \
                 'port:string'
 }
+validate_nfexpire_section() {
+        uci_validate_section nfcapd nfexpire "${1}" \
+                'max_space:string' \
+                'max_age:string'
+}
 
 start_service() {
         validate_nfcapd_section nfcapd || {
-                echo "validation failed"
+                echo "nfcapd configuration validation failed"
+                return 1
+        }
+        validate_nfexpire_section nfexpire || {
+                # NB: "validate" doesn't actuall check these options exist!
+                echo "nfexpire configuration validation failed"
                 return 1
         }
 
@@ -40,11 +50,15 @@ start_service() {
                 # Check and create storage directory
                 mkdir -p "$nfdirectory"
                 chown $nfuser:$nfuser "$nfdirectory"
+
+                # Use nfexpire to set autoexpiry settings
+                su $nfuser -s /bin/ash -c "/usr/bin/nfexpire -u $nfdirectory -s $max_space -t $max_age "
+
                 procd_open_instance
                 procd_set_param stdout 1
                 procd_set_param stderr 1
                 procd_set_param command "$PROG"
-                procd_append_param command -S 1 -P "$pidfile" -p "$port" -M "$nfdirectory" -w -u $nfuser -g $nfuser
+                procd_append_param command -S 1 -P "$pidfile" -p "$port" -M "$nfdirectory" -w -e -u $nfuser -g $nfuser
                 procd_close_instance
         }
 }
